// vue/city/src/components/City.vue
<template>
    <div class="City">
        <Header :title="title"></Header>
        <div class="CityTop">
            <h2>您已选择城市：</h2>
            <ul>
                <li v-for="(v,i) in citys" :key="i" v-html="v.city" @click="(e)=>{delCity(e,v.city)}"></li>
            </ul>
        </div>
        <div class="CityBox">
            <div v-for="(val,ind) in data" :key="ind" v-if='val.citys.length'>
                <h3 v-html="val.letter"></h3>
                <ul>
                    <li v-for="(v,i) in val.citys" :key="i" v-html="v" @click="(e)=>{giveCity(e,v)}" v-default ref="li"></li>
                </ul>
            </div>
        </div>
    </div>
</template>

<script>
import Header from "./Header"
import axios from "axios"
export default {
    data() {
        return {
            title: "城市",
            data: null,
            citys: [{ city: window.sessionStorage.getItem("address") }],
            li1: true,
        }
    },
    beforeRouteEnter(to, from, next) {
        axios.get("/api/citydata")
            .then((data) => {
                next((vm) => {
                    vm.data = data.data
                })
            })
    },
    mounted() {
        setTimeout(() => {
            this.$refs.li.forEach((v, i) => {
                if (v.innerHTML == window.sessionStorage.getItem("address")) {
                    this.citys[0].dom = v
                }
            })

        }, 0);
    },
    methods: {
        giveCity(e, v) {
            if (e.target.className != 'active') {
                if (this.citys.length < 5) {
                    e.target.className = "active"
                    this.citys.push({ city: v, dom: e.target })
                }
            }
            else {
                this.foreach(v)
            }
            window.sessionStorage.address = this.citys[0].city
        },
        delCity(e, v) {
            this.foreach(v)
        },
        foreach(v) {
            if (this.citys.length != 1) {
                this.citys.forEach((val, ind) => {
                    if (val.city == v) {
                        this.citys.splice(ind, 1)
                        val.dom.className = ""
                    }
                })
            }
            window.sessionStorage.address = this.citys[0].city
        }
    },
    components: {
        Header
    },
    directives: {
        default: {
            bind(el) {
                if (el.innerHTML == window.sessionStorage.getItem("address")) {
                    el.className = "active"
                }
            }
        }
    }
}
</script>

<style>
.City {
    width: 100%;
    height: 100%;
    background: #fff;
    position: fixed;
}

.CityTop {
    border-bottom: .01rem solid #ccc;
}

.CityTop h2 {
    line-height: .8rem;
    padding-left: .3rem;
    font-size: .3rem;
}

.CityBox {
    width: 100%;
    height: 100%;
    overflow-y: scroll;
}

.CityBox h3 {
    line-height: .5rem;
    padding-left: .2rem;
    font-size: .3rem;
}

.CityBox ul,
.CityTop ul {
    display: flex;
    flex-wrap: wrap;
}

.CityBox ul li,
.CityTop ul li {
    padding: .2rem;
    margin: .1rem;
    font-size: .25rem;
    border: .01rem solid transparent;
}

.CityBox ul li.active {
    border: .01rem solid red;
}
</style>

// react/买车+city/src/components/Home/City/City.jsx
import React, { Component } from "react"
import { connect } from "react-redux"
import "./City.css"
import axios from "axios"
import { NavLink } from "react-router-dom"

class City extends Component {
    constructor() {
        super()
        this.state = {
            citys: [{ city: sessionStorage.getItem("address") }],
            topCity: ""
        }
    }
    componentDidMount() {
        axios.get("/api/city").then((data) => {
            this.props.getData(data.data)
            for (let key in this.refs) {
                if (key == this.state.citys[0].city) {
                    this.state.citys[0].dom = this.refs[key]
                }
            }
            this.state.citys.forEach((v, i) => {
                v.dom.className = "active"
            })
            this.setState({ topCity: sessionStorage.getItem("topCity") })
        })
    }
    click(e) {
        if (e.target.className != 'active') {
            e.target.className = "active"
            this.setState([...this.state.citys.push({ city: e.target.innerHTML, dom: e.target })])
        }
        else {
            if (this.state.citys.length != 1) {
                this.state.citys.forEach((val, ind) => {
                    if (val.city == e.target.innerHTML) {
                        this.setState([...this.state.citys.splice(ind, 1)])
                        val.dom.className = ""
                    }
                })
            }
        }

    }
    del(e) {
        if (this.state.citys.length != 1) {
            this.state.citys.forEach((val, ind) => {
                if (val.city == e.target.innerHTML) {
                    this.setState([...this.state.citys.splice(ind, 1)])
                    val.dom.className = ""
                }
            })
        }
    }
    goBack() {
        sessionStorage.address = this.state.citys[0].city
    }
    render() {
        let { citys, topCity } = this.state
        return (
            <div className="City">
                <div className="head">
                    <NavLink to="/" onClick={this.goBack.bind(this)}> ＜ </NavLink> | <span>选择城市</span>
                    <NavLink to="/TopCity">上牌城市选择 ></NavLink>
                </div >

                <div className="title">
                    <span>您选择的上牌城市是:</span><b>{topCity}</b>
                </div>

                <div className="CityTop">
                    <h2>您已选择城市：</h2>
                    <ul>
                        {
                            citys.map((v, i) => {
                                return <li key={i} onClick={(e) => { this.del(e) }}>{v.city}</li>
                            })
                        }
                    </ul>
                </div>

                <div className="CityBox">
                    {
                        this.props.data.map((v, i) => {
                            return <div key={i}>
                                <h3>{v.letter}</h3>
                                <ul>
                                    {
                                        v.citys.map((val, ind) => {
                                            return <li key={ind} ref={val} onClick={(e) => { this.click(e) }}>{val}</li>
                                        })
                                    }
                                </ul>
                            </div>
                        })
                    }
                </div>
            </div>
        )
    }
}

const state = (state) => {
    return {
        data: state.city
    }
}

const action = (dispatch) => {
    return {
        getData: (data) => {
            dispatch({
                type: "getCityData",
                data: data
            })
        }
    }
}


export default connect(state, action)(City)
